workspace:
  path: /go/src/github.com/ypcloud/sonar-runner-plugin

pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo

  latest:
    image: docker
    repo: ypcloud/sonar-runner
    tags: [ "latest", "1.0", "1" ]
    when:
      branch: master
      event: push
